In [1]:
!apt-get install redis-server -y
!pip install redis dash pandas seaborn matplotlib plotly
!redis-server --daemonize yes

'apt-get' is not recognized as an internal or external command,
operable program or batch file.

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: redis in d:\btd\data visualization\.venv\lib\site-packages (5.2.1)
Requirement already satisfied: dash in d:\btd\data visualization\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: pandas in d:\btd\data visualization\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: seaborn in d:\btd\data visualization\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in d:\btd\data visualization\.venv\lib\site-packages (3.10.0)
Requirement already satisfied: plotly in d:\btd\data visualization\.venv\lib\site-packages (6.0.1)
Requirement already satisfied: async-timeout>=4.0.3 in d:\btd\data visualization\.venv\lib\site-packages (from redis) (5.0.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in d:\btd\data visualization\.venv\lib\site-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in d:\btd\data visualization\.venv\lib\site-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in d:\btd\data visualization\.venv\lib\site-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in d:\btd\data visualization\.venv\lib\site-packages (from dash) (4.12.2)
Requirement already satisfied: requests in d:\btd\data visualization\.venv\lib\site-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in d:\btd\data visualization\.venv\lib\site-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in d:\btd\data visualization\.venv\lib\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in d:\btd\data visualization\.venv\lib\site-packages (from dash) (65.5.0)
Requirement already satisfied: numpy>=1.22.4 in d:\btd\data visualization\.venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\btd\data visualization\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\btd\data visualization\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in d:\btd\data visualization\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\btd\data visualization\.venv\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: narwhals>=1.15.1 in d:\btd\data visualization\.venv\lib\site-packages (from plotly) (1.33.0)
Requirement already satisfied: Jinja2>=3.1.2 in d:\btd\data visualization\.venv\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in d:\btd\data visualization\.venv\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in d:\btd\data visualization\.venv\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in d:\btd\data visualization\.venv\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: six>=1.5 in d:\btd\data visualization\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in d:\btd\data visualization\.venv\lib\site-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in d:\btd\data visualization\.venv\lib\site-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\btd\data visualization\.venv\lib\site-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in d:\btd\data visualization\.venv\lib\site-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\btd\data visualization\.venv\lib\site-packages (from requests->dash) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\btd\data visualization\.venv\lib\site-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: colorama in d:\btd\data visualization\.venv\lib\site-packages (from click>=8.1.3->Flask<3.1,>=1.0.4->dash) (0.4.6)

'redis-server' is not recognized as an internal or external command,
operable program or batch file.

In [7]:
import redis
import pandas as pd
import pickle

#Connect to Redis
r = redis.Redis(host='localhost', port = 6379, db = 0)

#Load and Cache
def get_cached_dataset(key='restaurant_df', path='./data/Coffee Shop Sales.csv'):
  if r.exists(key):
    print("Loading from Redis cache...")
    return pickle.loads(r.get(key))
  else:
    print("Loading from csv and caching in Redis....")
    df = pd.read_csv(path)
    r.set(key, pickle.dumps(df))
    return df

#Load Data
df = get_cached_dataset()

#Preview
df.columns = df.columns.str.strip()
df['date'] = df['transaction_date'] + '-' +  df['transaction_time']
df.drop(['transaction_date', 'transaction_time'], axis=1, inplace=True)
df['date'] = pd.to_datetime(df['date'], format = "mixed")
df.set_index('date', inplace=True)
df.head()

Loading from Redis cache...

,transaction_id,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
date,,,,,,,,,
2023-01-01 07:06:11,1,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
2023-01-01 07:08:56,2,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2023-01-01 07:14:04,3,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
2023-01-01 07:20:24,4,1,5,Lower Manhattan,,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
2023-01-01 07:22:41,5,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 149116 entries, 2023-01-01 07:06:11 to 2023-06-30 20:57:19
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_qty   149116 non-null  int64
 2   store_id          149116 non-null  int64
 3   store_location    149116 non-null  object
 4   product_id        149116 non-null  object
 5   unit_price        149116 non-null  float64
 6   product_category  149116 non-null  object
 7   product_type      149116 non-null  object
 8   product_detail    149116 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 11.4+ MB

In [9]:
# add columns like month, day number, day name, is weekend
df['Month'] = df.index.month
df['Day'] = df.index.day
df['Day_name'] = df.index.day_name()

df['is_weekend'] = df.index.weekday > 4

df['Hour'] = df.index.hour

df['revenue'] = df['transaction_qty'] * df['unit_price']


daily_sales = df['transaction_qty'].resample('D').sum()
missing_days = daily_sales.isna().sum()


df.head()

,transaction_id,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Month,Day,Day_name,is_weekend,Hour,revenue
date,,,,,,,,,,,,,,,
2023-01-01 07:06:11,1,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,1,1,Sunday,True,7,6.0
2023-01-01 07:08:56,2,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,1,1,Sunday,True,7,6.2
2023-01-01 07:14:04,3,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,1,1,Sunday,True,7,9.0
2023-01-01 07:20:24,4,1,5,Lower Manhattan,,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,1,1,Sunday,True,7,2.0
2023-01-01 07:22:41,5,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,1,1,Sunday,True,7,6.2

In [11]:
daily_summary = df.resample('D').agg({
    'transaction_qty': 'sum',
    'revenue': 'sum'
})

daily_summary

            transaction_qty  revenue
date
2023-01-01              802  2508.20
2023-01-02              796  2466.30
2023-01-03              968  3040.25
2023-01-04             1198  3699.90
2023-01-05             1515  4731.45
...                     ...      ...
2023-12-02              872  2894.00
2023-12-03              947  3088.33
2023-12-04             1239  4040.18
2023-12-05             1493  4681.13
2023-12-06             1674  5328.70

[340 rows x 2 columns]

In [13]:
df.isnull().sum()

transaction_id      0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
Month               0
Day                 0
Day_name            0
is_weekend          0
Hour                0
revenue             0
dtype: int64